export enum CodigoError {
  ADMIN_SERVER_ERROR = 'ADMIN_SERVER_ERROR',
  APPCLIENTE_CREACION_ERROR = 'APPCLIENTE_CREACION_ERROR',
  
  VALIDACION = 'VALIDACION',
  TERMINAL_NO_ENCONTRADA = 'TERMINAL_NO_ENCONTRADA',

  CERTIFICADOS = 'CERTIFICADOS',

  AFIP_TIMEOUT = 'AFIP_TIMEOUT',
  AFIP_NO_DISPONIBLE = 'AFIP_NO_DISPONIBLE',
  AFIP_ERROR = 'AFIP_ERROR',
  AFIP_RECHAZO = 'AFIP_RECHAZO',
  QR_ERROR = 'QR_ERROR',

  AUTH_NO_HABILITADO = 'AUTH_NO_HABILITADO',

  // Entorno de ejecucion (NODE_ENV / config.produccion / parametro 'entorno' en DB)
  // inconsistente. Bloquea la facturacion (fail-closed) sin tirar el proceso.
  ENTORNO_INVALIDO = 'ENTORNO_INVALIDO',

  // F1 - HANDOFF blindaje facturacion y logs
  CORRELATIVIDAD_ARCA = 'CORRELATIVIDAD_ARCA',
  FACTURACION_EN_CURSO = 'FACTURACION_EN_CURSO',
  COMPROBANTE_INCIERTO = 'COMPROBANTE_INCIERTO',
  COMPROBANTE_RECUPERADO = 'COMPROBANTE_RECUPERADO',
  NETO_DESCALCE = 'NETO_DESCALCE',
  STOCK_INSUFICIENTE = 'STOCK_INSUFICIENTE',

  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
